flowchart TD
aaa --> fft
bbb --> tty
ccc --> ddd
ccc --> eee
dac --> fff
ddd --> hub
eee --> dac
fff --> ggg
fff --> hhh
fft --> ccc
ggg --> out
hhh --> out
hub --> fff
svr --> aaa
svr --> bbb
tty --> ccc