flowchart TD
aaa --> you
aaa --> hhh
bbb --> ddd
bbb --> eee
ccc --> ddd
ccc --> eee
ccc --> fff
ddd --> ggg
eee --> out
fff --> out
ggg --> out
hhh --> ccc
hhh --> fff
hhh --> iii
iii --> out
you --> bbb
you --> ccc
